'use strict';

var config = {
    appId : "amzn1.ask.skill.20034481-27aa-4d91-8a6c-c52ea4a0d377",
    items_per_prompt : {
      show: 3,
      explainer: 3,
      episode: 3,
    },
    states: {
      START: '',
      HOME_PAGE: '_HOME_PAGE',
      PLAYING_EXPLAINER: '_PLAYING_EXPLAINER',
      ITERATING_EXPLAINER: '_ITERATING_EXPLAINER',
      REQUEST: '_REQUEST',
      CHANGE_INFO: '_CHANGE_INFO',
      UNRESOLVED: '_UNRESOLVED'
    },
    intents: {
      'AMAZON.HelpIntent': [
        "help",
        "help me",
        "can you help",
        "can you help me",
        "what do i do",
        "help please"
      ],
      'AMAZON.StopIntent': [
        "stop",
        "cancel",
        "I'm done",
        "I'm set",
        "I'm good",
        "I'm all set",
        "Enough",
        "That's enough",
        "I'm good thanks",
        "I'm all set",
        "All set",
        "All set, thanks",
        "All done, thanks",
        "All done",
        "Done",
        "I'm done",
        "I'm done thanks"
      ],
      HomePage: [
        "a main menu",
        "the main menu",
        "start menu",
        "home menu",
        "main menu",
        "home page",
        "start over",
        "what's new",
        "hear what's new",
        "tell me what's new",
        "tell me what is new",
        "what is new",
        "hear new explainers",
        "make me smart",
        "what I need to know",
        "what's happening in the world"
      ],
      ReplayExplainer: [
        "replay",
        "replay that",
        "restart",
        "play again",
        "play that again",
        "again",
        "let me hear that again",
        "start over",
        "replay explainer",
        "let's hear that again",
        "repeat",
        "begin again",
        "begin that again",
        "one more time",
        "replay today's explainer",
        "replay that exlplainer"
      ],
      PlayLatestExplainer: [
        "play all",
        "all of them",
        "all of em",
        "play all of em",
        "play them all",
        "play the latest",
        "the latest",
        "all",
        "latest topic",
        "the latest explainer",
        "latest explainer",
        "today's topic",
        "the latest",
        "play today's topic",
        "today's explainer",
        "play today's explainer",
        "play the latest explainer"
      ],
      RequestExplainer: [
        "pitch",
        "pitch explainer",
        "pitch an explainer",
        "pitch a new explainer",
        "pitch an explainer topic",
        "pitch a topic",
        "propose",
        "propose explainer",
        "propose an explainer",
        "propose a new explainer",
        "propose an explainer topic",
        "propose a topic",
        "propose an idea",
        "request",
        "make a request",
        "request an explainer",
        "request explainer",
        "request a topic",
        "request a new topic",
        "request a new explainer",
        "i want to request something",
        "i want to make a request",
        "i want to pitch something",
        "submit",
        "submission",
        "make a submission",
        "submit explainer",
        "submit an explainer",
        "submit my explainer",
        "submit my explainer idea",

        "submit my idea",
        "submit my idea",
        "submit an idea for your next one",
        "submit an idea for your next explainer",

        "submit an idea for what we should explain next",
        "submit my idea for what you should explain next",
        "submit idea",
        "submit your idea",
        "submit an idea",
        "submit an idea for an explainer",
        "submit an idea for a new explainer",

        "submit a topic",
        "submit a topic idea",
        "i want to submit a topic",
        "can i make a submission",
        "i want to submit something",
        "i want to submit a topic",
        "suggest",
        "suggestion",
        "make a suggestion",
        "suggest an explainer",
        "suggest a topic",
        "i want to suggest a topic",
        "can i make a suggestion",
        "i want to suggest something",
        "i want to suggest a topic",
        "idea",
        "new idea",
        "new explainer",
        "I've got an idea",
        "I've got an idea for an explainer",
        "I've got an explainer idea",
        "topic",
        "new topic",
        "I've got an idea for a topic"
      ],
      ListExplainers: [
        "explainer menu",
        "what explainers it has",
        "what you got",
        "what you have",
        "list",
        "list all",
        "list explainers",
        "list all our explainers",
        "list our explainers",
        "list your explainers",
        "list the explainers",
        "list all explainers",
        "everything",
        "explore",
        "explore explainers",
        "explore all",
        "explore our explainers",
        "explore your explainers",
        "explore the explainers",
        "explore all explainers",
        "explore all our explainers",
        "explore all the explainers",
        "browse",
        "browse explainers",
        "browse all",
        "browse all explainers",
        "browse our explainers",
        "browse the explainers",
        "browse your explainers",
        "browse all our explainers",
        "all explainers",
        "see all explainers",
        "show all explainers",
        "show me all explainers",
        "show me all the explainers",
        "show me more",
        "ask for more",
        "more options",
        "more",
        "more please",
        "more explainers"
      ],
      EarlierExplainers: [
        "earlier",
        "earlier explainers",
        "before that",
        "further back",
        "older",
        "older 3",
        "older explainers",
        "older explainer",
        "go back"
      ],
      LaterExplainers: [
        "later",
        "later explainers",
        "after that",
        "more recent",
        "more recent 3",
        "newer",
        "newer explainers",
        "newer explainer"
      ],
      ChangeMyInfo: [
        "change my name",
        "change my info",
        "correct name",
        "update name",
        "change info",
        "correct my name",
        "update my name",
        "change my city",
        "change my location",
        "correct location",
        "update location",
        "correct my location",
        "update my city",
        "add my info",
        "add my name",
        "add my city",
        "add info",
        "add name",
        "add city"
      ]
    },
    defaultDescription: "Something else you want to get smart about? Try 'Alexa, submit an idea' and Kai and Molly might use your idea!",
    newUserAudio: 'https://s3.amazonaws.com/alexa-marketplace-make-me-smart/utils/Alexa+-+Ryssdal+-+Wood+-+Welcome+New+User+Message+-+MIXLEV_alexa.mp3',
    background: {
      show: "https://s3.amazonaws.com/alexa-marketplace-make-me-smart/1024x600_FINALB.png"
    },
    icon : {
      full: "https://s3.amazonaws.com/alexa-marketplace-make-me-smart/icon_full.png"
    },
    cacheExpiry: 1000 * 60 * 60 * 60 * 3, // 2 hour, but for this spin-up, right? should I persist?
    dynamoDBTableName: 'makeMeSmart',
    sessionDBName: 'session_info',
    constants: {
      breakTime : {
        '10' : '<break time = "10ms"/>',
        '25' : '<break time = "25ms"/>',
          '50' : '<break time = "50ms"/>',
          '100' : '<break time = "100ms"/>',
          '200' : '<break time = "200ms"/>',
          '250' : '<break time = "250ms"/>',
          '300' : '<break time = "300ms"/>',
          '500' : '<break time = "500ms"/>'
      },

    },
};

module.exports = config;
